const TYPE = {
  MINING_DONE_A_BLOCK: "MINING_DONE_A_BLOCK",
  NEW_BLOCK_ADD: "NEW_BLOCK_ADD",
  SEND_TRANSACTION: "SEND_TRANSACTION",
  NEW_TRANSACTION: "NEW_TRANSACTION",
  START_MINING: "START_MINING",
  STOP_MINING: "STOP_MINING",
  MINING_ABLOCK: "MINING_ABLOCK",
  LOGIN: "LOGIN",
  LAST_BLOCK: "LAST_BLOCK",
  VOTE_NEW_BLOCK: "VOTE_NEW_BLOCK",
  GET_BALANCE: "GET_BALANCE",
  GET_BLOCKCHAIN: "GET_BLOCKCHAIN",
  HISTORY_BLOCKCHAIN: "HISTORY_BLOCKCHAIN",
};

export default TYPE;
